[package]
name = "bolh-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]
name = "bolh_ffi"

[dependencies]
bolh-chain = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
