name: bolh
region: lon1

services:
  - name: api
    http_port: 8080
    github:
      repo: bertogassin/BOLH
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: .
    routes:
      - path: /api
      - path: /health
      - path: /users
    envs:
      - key: API_ADDR
        value: ":8080"
        scope: RUN_TIME

  - name: web
    http_port: 3003
    github:
      repo: bertogassin/BOLH
      branch: main
      deploy_on_push: true
    source_dir: guardian/client-web
    build_command: npm ci && npm run build
    run_command: npm run start
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${api.PUBLIC_URL}
        scope: RUN_AND_BUILD_TIME
